version: '3'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./docker/Dockerfile
    networks:
      - common
    ports:
      - 5432:5432
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: ./docker/Dockerfile
    networks:
      - common
    ports:
      - 8080:15672
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./api/:/app/
    command: bash -c "yarn dev"
    networks:
      - common
    ports:
      - 8081:3005
    depends_on:
      - airflow
      - rabbitmq
  airflow-server:
    build:
      context: ./airflow-server
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./airflow-server/:/app/
    command: bash -c "yarn dev"
    networks:
      - common
    ports:
      - 8081:3005
    depends_on:
      - airflow
      - rabbitmq
  airflow:
    build:
      context: ./airflow
      dockerfile: ./docker/Dockerfile
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
      - AIRFLOW_CONN_POSTGRES_MASTER=postgres://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    command: webserver
    networks:
      - common
    ports:
      - 8082:8080
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - postgres
      - rabbitmq


networks:
  common: